language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# install dependencies
before_install: cd graphpy
install: "pip install -r requirements.txt"
# run tests
script: nosetests
