language: python
python:
  - "2.7"
# install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# run tests
script: nosetests --with-coverage --cover-package=graphpy
after_success: coveralls
notifications:
  email: false
