language: python
python:
  - "2.7"
# install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install coveralls"
# run tests
script: coverage run --source=graphpy,nosetests
after_success: coveralls
notifications:
  email: false
