language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# install dependencies
install: "pip install -r requirements.txt"
# run tests
before_script: cd graphpy
script: nosetests
